### ISSUE TITLE
Extracting Snap and Wai interfaces into sub-packages

### ISSUE THREAD

**Issue by avanov** [dylex/web-inv-route#1]
Hi!

I wonder if you're open to the idea of moving Snap- and Wai-specific interfaces into their respective sub-packages. My primary motivation for this is decoupling projects using this library from [snap-core](https://hackage.haskell.org/package/snap-core) that has a significant list of transitive dependencies compared to [wai](https://hackage.haskell.org/package/wai), and this affects build times and migration efforts (to newer versions of GHC) Wai users have to go through without benefit to them.

**Comment by dylex** [comment]
I'm open to it, though if you're using stack or cabal, you can just disable the "snap" flag to remove this dependency.  This is what I do, for example here: https://github.com/flatironinstitute/flathub/blob/main/stack.yaml#L13
Would that work for you?

**Comment by avanov** [comment]
Oh, I didn't see the list of flags on Hackage because it was collapsed in the UI. That will work for me as well, thanks!
